# Tabular Data

## DataFrames

### Exercise 6
Load two years of stock data for every ticker in the current S&P 500. Perform the following:  

a. ‘Stack’ the table to get it into row form, and demonstrate ‘unstack’ to get it back into the original form.  
b. Melt and unmelt the table (using pivot), as shown in the lecture.  
c. Demonstrate usage of pivot_table.  
d. Create a derived table (a.k.a a ‘summary table’), containing the total volume (in millions) per year, of each ticker.  
e. Create a derived table containing the total volume (in millions) of each ticker.  
f. Add a column to the original table containing the daily return per ticker (using the above formula).  
g. Add a column to the original table containing the 1-week (5-day) moving average daily return, per ticker.  
h. Add a column to the original table containing the rolling cumulative sum of volume per ticker.

In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [21]:
import pandas as pd
import yfinance as yf

# Get the table of all stocks in the S&P 500 from Wikipedia
payload=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
first_table = payload[0]
second_table = payload[1]
gspcSummary = first_table
gspcSummary  # Display the wiki table of S&P500

gspcList = list(gspcSummary.Symbol)  # Put all the symbol into a list
gspcList

# Remove invalid symbol with no data from yf
gspcList.remove('BRK.B')  
gspcList.remove('BF.B')

# Download data into a multiindex table
tickers = yf.Tickers(gspcList)
hist = tickers.history(group_by='ticker', period='max')
hist.head()

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",1976-08-09,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,ABIOMED Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet Holdings,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,1952

['MMM',
 'ABT',
 'ABBV',
 'ABMD',
 'ACN',
 'ATVI',
 'ADBE',
 'AMD',
 'AAP',
 'AES',
 'AFL',
 'A',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALXN',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'ABC',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'AIV',
 'AAPL',
 'AMAT',
 'APTV',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'BKR',
 'BLL',
 'BAC',
 'BK',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'BIIB',
 'BLK',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BF.B',
 'CHRW',
 'COG',
 'CDNS',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'CNC',
 'CNP',
 'CERN',
 'CF',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CTXS',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'CXO',
 'COP',
 'ED',
 'STZ',
 'COO',
 'CPRT',
 'GLW',
 'CTVA',
 'COST',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHI',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DISCA',
 'DISCK',
 'DISH',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DTE',
 'DUK',
 'DRE',
 'DD',
 'DXC',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'EMR',
 'ETR',
 'EOG',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EVRG',
 'ES',
 'RE',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FB',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FE',
 'FRC',
 'FISV',
 'FLT',
 'FLIR',
 'FLS',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FBHS',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GPS',
 'GRMN',
 'IT',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GL',
 'GPN',
 'GS',
 'GWW',
 'HAL',
 'HBI',
 'HIG',
 'HAS',
 'HCA',
 'PEAK',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HFC',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUM',
 'HBAN',
 'HII',
 'IEX',
 'IDXX',
 'INFO',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'INTC',
 'ICE',
 'IBM',
 'IP',
 'IPG',
 'IFF',
 'INTU',
 'ISRG',
 'IVZ',
 'IPGP',
 'IQV',
 'IRM',
 'JKHY',
 'J',
 'JBHT',
 'SJM',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'KSU',
 'K',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LB',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LEG',
 'LDOS',
 'LEN',
 'LLY',
 'LNC',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LUMN',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MKC',
 'MXIM',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MHK',
 'TAP',
 'MDLZ',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'MYL',
 'NDAQ',
 'NOV',
 'NTAP',
 'NFLX',
 'NWL',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NLSN',
 'NKE',
 'NI',
 'NSC',
 'NTRS',
 'NOC',
 'NLOK',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PBCT',
 'PEP',
 'PKI',
 'PRGO',
 'PFE',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PSA',
 'PHM',
 'PVH',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SEE',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SLG',
 'SNA',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STE',
 'SYK',
 'SIVB',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TGT',
 'TEL',
 'FTI',
 'TDY',
 'TFX',
 'TER',
 'TXN',
 'TXT',
 'TMO',
 'TIF',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TFC',
 'TWTR',
 'TYL',
 'TSN',
 'UDR',
 'ULTA',
 'USB',
 'UAA',
 'UA',
 'UNP',
 'UAL',
 'UNH',
 'UPS',
 'URI',
 'UHS',
 'UNM',
 'VFC',
 'VLO',
 'VAR',
 'VTR',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VIAC',
 'V',
 'VNT',
 'VNO',
 'VMC',
 'WRB',
 'WAB',
 'WMT',
 'WBA',
 'DIS',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WU',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WLTW',
 'WYNN',
 'XEL',
 'XRX',
 'XLNX',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZION',
 'ZTS']

[*********************100%***********************]  503 of 503 completed

            CXO                                              CHRW           \
           Open High Low Close Volume Dividends Stock Splits Open High Low
Date
1962-01-02  NaN  NaN NaN   NaN    NaN       NaN          NaN  NaN  NaN NaN
1962-01-03  NaN  NaN NaN   NaN    NaN       NaN          NaN  NaN  NaN NaN
1962-01-04  NaN  NaN NaN   NaN    NaN       NaN          NaN  NaN  NaN NaN
1962-01-05  NaN  NaN NaN   NaN    NaN       NaN          NaN  NaN  NaN NaN
1962-01-08  NaN  NaN NaN   NaN    NaN       NaN          NaN  NaN  NaN NaN

            ...    KEY                               GE                      \
            ... Volume Dividends Stock Splits      Open      High       Low
Date        ...
1962-01-02  ...    NaN       NaN          NaN  0.125432  0.127523  0.124178
1962-01-03  ...    NaN       NaN          NaN  0.124387  0.124387  0.123342
1962-01-04  ...    NaN       NaN          NaN  0.123760  0.124805  0.121251
1962-01-05  ...    NaN       NaN          NaN  0.122297  0.122506  0.117070
1962-01-08  ...    NaN       NaN          NaN  0.119161  0.119161  0.115398


               Close     Volume Dividends Stock Splits
Date
1962-01-02  0.125014  2156500.0       0.0          0.0
1962-01-03  0.123760  1477600.0       0.0          0.0
1962-01-04  0.122297  1837000.0       0.0          0.0
1962-01-05  0.119161  2725600.0       0.0          0.0
1962-01-08  0.118952  3095000.0       0.0          0.0

[5 rows x 3521 columns]

#### a. ‘Stack’ the table to get it into row form, and demonstrate ‘unstack’ to get it back into the original form.

In [23]:
# Stack the table
hist.stack(level=0).reset_index().rename(columns = {'level_1':'Ticker'})

# Unstack the table
hist.stack(level=0).unstack()

,Date,Ticker,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,1962-01-02,BA,0.187037,0.0,0.190310,0.187037,0.190310,0.0,352200.0
1,1962-01-02,CAT,0.134703,0.0,0.136015,0.133391,0.134703,0.0,163200.0
2,1962-01-02,CVX,0.050512,0.0,0.050512,0.049714,0.000000,0.0,105600.0
3,1962-01-02,DIS,0.058360,0.0,0.060318,0.058360,0.058360,0.0,817400.0
4,1962-01-02,DTE,0.484267,0.0,0.489250,0.484267,0.000000,0.0,1600.0
...,...,...,...,...,...,...,...,...,...
3900541,2020-10-16,YUM,98.529999,0.0,100.750000,98.410004,99.669998,0.0,2282000.0
3900542,2020-10-16,ZBH,146.929993,0.0,149.350006,146.729996,148.270004,0.0,770300.0
3900543,2020-10-16,ZBRA,293.000000,0.0,295.369995,289.239990,289.959991,0.0,218800.0
3900544,2020-10-16,ZION,31.139999,0.0,31.330000,30.459999,31.100000,0.0,1831200.0
3900545,2020-10-16,ZTS,163.550003,0.0,165.850006,163.320007,163.979996,0.0,1631000.0

                 Close                                                       \
                     A    AAL         AAP        AAPL       ABBV        ABC
Date
1962-01-02         NaN    NaN         NaN         NaN        NaN        NaN
1962-01-03         NaN    NaN         NaN         NaN        NaN        NaN
1962-01-04         NaN    NaN         NaN         NaN        NaN        NaN
1962-01-05         NaN    NaN         NaN         NaN        NaN        NaN
1962-01-08         NaN    NaN         NaN         NaN        NaN        NaN
...                ...    ...         ...         ...        ...        ...
2020-10-12  105.430000  12.92  156.250000  124.400002  87.133415  96.860001
2020-10-13  105.419998  12.22  157.380005  121.099998  86.650002  97.269997
2020-10-14  105.059998  12.36  156.580002  121.190002  86.070000  98.440002
2020-10-15  105.320000  12.23  157.520004  120.709999  85.230003  99.349998
2020-10-16  106.699997  12.46  154.990005  119.019997  86.269997  99.519997

                                                            ...     Volume  \
                  ABMD         ABT         ACN        ADBE  ...       XLNX
Date                                                        ...
1962-01-02         NaN         NaN         NaN         NaN  ...        NaN
1962-01-03         NaN         NaN         NaN         NaN  ...        NaN
1962-01-04         NaN         NaN         NaN         NaN  ...        NaN
1962-01-05         NaN         NaN         NaN         NaN  ...        NaN
1962-01-08         NaN         NaN         NaN         NaN  ...        NaN
...                ...         ...         ...         ...  ...        ...
2020-10-12  277.850006  110.681099  230.589996  510.890015  ...  4829300.0
2020-10-13  276.950012  108.010002  229.380005  514.309998  ...  2457400.0
2020-10-14  280.839996  107.750000  229.429993  506.309998  ...  2473200.0
2020-10-15  283.570007  107.320000  228.770004  501.149994  ...  2532500.0
2020-10-16  286.480011  109.669998  230.050003  502.820007  ...  3517900.0

                                                                              \
                   XOM      XRAY        XRX        XYL        YUM        ZBH
Date
1962-01-02    902400.0       NaN        NaN        NaN        NaN        NaN
1962-01-03   1200000.0       NaN        NaN        NaN        NaN        NaN
1962-01-04   1088000.0       NaN        NaN        NaN        NaN        NaN
1962-01-05   1222400.0       NaN        NaN        NaN        NaN        NaN
1962-01-08   1388800.0       NaN        NaN        NaN        NaN        NaN
...                ...       ...        ...        ...        ...        ...
2020-10-12  17912800.0  582300.0  1675300.0   775300.0   976900.0   964000.0
2020-10-13  20995100.0  600500.0  1705700.0   768700.0   847600.0  1211300.0
2020-10-14  17756500.0  626900.0  1849100.0   776900.0  1317000.0   858500.0
2020-10-15  23251600.0  657300.0  1480900.0   532100.0  2427900.0   991000.0
2020-10-16  22627200.0  819100.0  2051800.0  1506300.0  2282000.0   770300.0


                ZBRA       ZION        ZTS
Date
1962-01-02       NaN        NaN        NaN
1962-01-03       NaN        NaN        NaN
1962-01-04       NaN        NaN        NaN
1962-01-05       NaN        NaN        NaN
1962-01-08       NaN        NaN        NaN
...              ...        ...        ...
2020-10-12  277900.0   980500.0  1582300.0
2020-10-13  227300.0  1123200.0  1515800.0
2020-10-14  345600.0  1348800.0  1319500.0
2020-10-15  204300.0  1852700.0  1363800.0
2020-10-16  218800.0  1831200.0  1631000.0

[14821 rows x 3521 columns]

#### b. Melt and unmelt the table (using pivot), as shown in the lecture.