# Data Research

## Intro to Machine Learning

### Exercise 1
Use the dataset to perform a regression prediction using scikit-learn, as demonstrated in the lectures. You should split the data into test/train sets, train the model (output/comment the
scores), cross validate the model (output/comment the scores), and predict using the test set (output/comment the scores and actual accuracy).

In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Load data
%store -r data
aaplData = data
aaplData

,Date,High,Low,Open,Close,Volume,Adj Close,Daily Return,1-week MA Volume,1-week MA Daily Return,Ticker
5,2015-11-02,30.340000,29.902500,30.200001,30.295000,128813200.0,27.996040,0.014059,230585360.0,0.010190,AAPL
6,2015-11-03,30.872499,30.174999,30.197500,30.642500,182076000.0,28.317165,0.011471,211093040.0,0.013750,AAPL
7,2015-11-04,30.955000,30.405001,30.782499,30.500000,179544400.0,28.185480,-0.004650,178560800.0,0.004579,AAPL
8,2015-11-05,30.672501,30.045000,30.462500,30.230000,158210800.0,28.055548,-0.008852,169221120.0,0.000696,AAPL
9,2015-11-06,30.452499,30.155001,30.277500,30.264999,132169200.0,28.088028,0.001158,156162720.0,0.002637,AAPL
...,...,...,...,...,...,...,...,...,...,...,...
1254,2020-10-19,98.761624,96.489998,119.959999,115.980003,120639300.0,115.980003,-0.025542,152397020.0,-0.013857,AAPL
1255,2020-10-20,98.761624,96.489998,116.199997,117.510002,124423700.0,117.510002,0.013192,124815660.0,-0.005914,AAPL
1256,2020-10-21,98.761624,96.489998,116.669998,116.870003,89946000.0,116.870003,-0.005446,112592400.0,-0.007152,AAPL
1257,2020-10-22,98.761624,96.489998,117.449997,115.750000,101709700.0,115.750000,-0.009583,110422500.0,-0.008276,AAPL
1258,2020-10-23,98.761624,96.489998,116.389999,115.040001,79629035.0,115.040001,-0.006134,103269547.0,-0.006703,AAPL